version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "4000:4000"
    networks:
      - ai
    restart: always

networks:
  ai:
